final Map<String, String> enTranslation = {
  "createnew": "Create New",
  "password": "Password",
  "createstrongandsecurepasswordthatprotectyouraccount":
      "Create strong and secure password that protect your account",
  "save": "Save",
  "enteryourpassword": "Enter your password",
  "yourpasswordisincorrect": "Your password is incorrect",
  "enteryourconfirmpassword": "Enter your confirm password",
  "passworddontmatch": "Password don't match",
  "findpassword": "Find password",
  "options": "Options",
  "pleaseselectoptiontosendlinkresetpassword":
      "Please select option to send link reset password",
  "resetviaemail": "Reset via email",
  "ifyouhaveemaillinkedtoaccount": "If you have email linked to account",
  "resetviasms": "Reset via sms",
  "skip": "Skip",
  "start": "Start",
  "next": "Next",
  "welcometodigitalpost": "Welcome To Digital Post",
  "allbussinessbrandingpost": "All Bussiness Branding Post",
  "festivalcategorypost": "Festival Category Post",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustry":
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  "videocategorypost": "Video Category Post",
  "login": "Login",
  "signup": "Sign Up",
  'myprofile': 'My Profile',
  "businessname": "Business Name",
  "enterbusinessname": "Enter business Name",
  "pleaseentervalidaddress": "Please Enter Your Address",
  "businesscategory": "Business Category",
  "address": "Enter Address",
  "enteryouraddress": "Enter Your Address",
  "alternativephonenumber": "Alternative Phone Number",
  "welcomeback": "Welcome back!",
  "enteryouremail": "Enter your E-mail",
  "rememberme": "Remember me",
  "forgetpassword": "Forget Password",
  "orloginwith": "Or log in with",
  "yes": "Yes",
  "no": "No",
  "registerinbyenteringyouraccountdetails":
      "Register in by entering your account details.",
  "firstname": "First Name",
  "lastname": "Last Name",
  "enterfirstname": "Enter first Name",
  "enterlastname": "Enter Last Name",
  "emailaddress": "E-mail Address",
  "recovery": "Recovery",
  "pleaseenteryouremailtorecoveryourpassword":
      "Please enter your email to recover your password",
  "sendlink": "Send Link",
  "wecannotfindanaccountwiththatemailaddress":
      "We cannot find an account with that email address",
  "enteryourfullname": "Enter your full name",
  "entervalidemail": "Enter valid E-mail",
  "postervibe": "postervibe",
  "version": "Version",
  "verification": "Verification",
  "code": "Code",
  "verificationcodewassentto": "Verification code was sent to",
  "resendcodein": "Resend code in",
  "resend": "Resend",
  "sendcode": "Send Code",
  "pleaseentervalidotp": "Please enter valid otp",
  "verifyphone": "Verify Phone",
  "number": "Number",
  "pleaseconfirmyourcountrycodeandenteryourphonenumber":
      "Please confirm your country code and enter your phone number",
  "phonenumber": "Phone Number",
  "downloads": "Downloads",
  "review": "Review",
  "invitefriends": "Invite Friends",
  "help": "Help",
  "logout": "Log Out",
  "upgradetopro": "Upgrade to PRO",
  "oneyearsupportmonthlyupdatesforupto5teammembers":
      "One year support, monthly updates for up to 5 team members.",
  "contactus": "Contact Us",
  "email": "Email",
  "phone": "Phone",
  "name": "Name",
  "writeyourmessagehere": "Write your message here",
  "add": "Add",
  "namefieldrequired": "Name field required",
  "emailfieldrequired": "Email field required",
  "messagefieldrequired": "Message field required",
  "digitalpost": "Digital Post",
  "all": "All",
  "gujrati": "Gujarati",
  "hindi": "Hindi",
  "english": "English",
  "images": "Images",
  "videos": "Videos",
  "editprofile": "Edit Profile",
  "entername": "Enter Name",
  "enteremail": "Enter email",
  "birthdate": "Birth date",
  "thefullnamefieldisrequired": "The full name field is required",
  "theemailfieldisrequired": "The email field is required",
  "thephonenumberfieldisrequired": "The Phone number field is required",
  "pleaseentervalidphonenumber": "Please enter valid phone number",
  "pleaseenteryourphonenumber": "Please enter your phone number",
  "thebirthdatefieldisrequired": "The birth date field is required",
  "favorite": "Favorite",
  "filters": "Filters",
  "posttype": "Post Type",
  "festival": "Festival",
  "bussiness": "Bussiness",
  "marketing": "Marketing",
  "image": "Image",
  "video": "Video",
  "free": "Free",
  "premium": "Premium",
  "horizontal": "Horizontal",
  "vertical": "Vertical",
  "square": "Square",
  "panoramic": "Panoramic",
  "categorytype": "Category Type",
  "licensetype": "License Type",
  "colortype": "Color Type",
  "orientationtype": "Orientation Type",
  "faq": "FAQ",
  "faqandsupport": "FAQ and Support",
  "didntfindtheansweryouwerelookingforcontactoursupportcenter":
      "Didn't find the answer you were looking for? Contact our support center!",
  "gotoourwebsite": "Go to our Website",
  "emailus": "Email Us",
  "termsofservice": "Terms of Service",
  "search": "Search",
  "howdoichangemypassword": "How do I change my password?",
  "tochangeyourpasswordproceedtomenuandselectaprofilethenretypeyourcurrentpasswordandclickconfirm":
      "To change your password, proceed to menu and select a profile. Then retype your current password and click confirm.",
  "diwali": "Diwali",
  "holi": "Holi",
  "makarsankranti": "Makar Sankranti",
  "upcomingfestival": "Upcoming Festival",
  "videocategory": "Video Category",
  "upcamingdayfestival": "Upcaming Day / Festival",
  "viewall": "View All",
  "whenyourfrindssignupwithyourlinkyoullbothgetcharge":
      "When your frinds sign up with your link you’ll both get \$20 charge",
  "link": "Link",
  "pleaseenteravalidlink": "Please enter a valid Link",
  "language": "Language",
  "searchlanguages": "Search languages",
  "notifications": "Notifications",
  "nonotificationyet": "No Notification Yet",
  "whenyougetnotificaiontheyllshowuphere":
      "When you get notificaion, they'll show uphere",
  "return": "Return",
  "searchnotifications": "Search Notifications",
  "payment": "Payment",
  "addnewcard": "Add New Card",
  "addyourdebitcreaditcard": "Add your debit/creadit card",
  "cardholdername": "Card Holder Name",
  "month": "Month",
  "year": "Year",
  "entervalidname": "Enter valid Name",
  "entervalidnumber": "Enter valid number",
  "thecardnumbermustcontainatleast16character":
      "The Card Number must contain at least 16 character",
  "selectexpiredate": "Select Expire Date",
  "entersecuritycode": "Enter Security Code",
  "thesecuritycodemustcontainatleast3character":
      "The Security Code must contain at least 3 character",
  "premiumaccess": "Premium Access",
  "umlimitedpostandvideos": "Umlimited Post And Videos",
  "sharemanagepostvideos": "Share & Manage Post & Videos",
  "automaticdownload": "Automatic Download",
  "week": "Week",
  "yearly": "Yearly",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "3daysfreetrialthenmonthisnotcancelled":
      "3-days free trial then \$6.99/month is not cancelled",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustryloremipsumhasbeentheindustrysstandarddummytexteversincethe1500swhenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook":
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  "preview": "Preview",
  "profile": "Profile",
  "setting": "Setting",
  "notification": "Notification",
  "shareyourmessagewithothertaxipassenger":
      "Share your message with other taxi passenger.",
  "submit": "Submit",
  "settings": "Settings",
  "option": "Option",
  "thememode": "Theme mode",
  "dark": "Dark",
  "light": "Light",
  "account": "Account",
  "personalinformation": "Personal Information",
  "general": "General",
  "touchidandpasscode": "Touch ID and Passcode",
  "privacy": "Privacy",
  "other": "Other",
  "facebook": "Facebook",
  "appshare": "App share",
  "share": "Share",
  "shareyourlink": "Share your Link",
  "sharetoyourfriendbyusingthese": "Share to your friend by using these",
  "areyousureyouwanttologout": "Are you sure you want to logout",
  "cancel": "Cancel",
};
