final Map<String, String> guTranslation = {
  "createnew": "નવું બનાવો",
  "password": "પાસશ",
  "createstrongandsecurepasswordthatprotectyouraccount":
      "મજબૂત અને સુરક્ષિત પાસવર્ડ બનાવો જે તમારા એકાઉન્ટને સુરક્ષિત કરે છે",
  "save": "બચત કરવી",
  "enteryourpassword": "તમારો પાસવર્ડ નાખો",
  "yourpasswordisincorrect": "તમારો પાસવર્ડ ખોટો છે",
  "enteryourconfirmpassword": "તમારો પુષ્ટિ પાસવર્ડ દાખલ કરો",
  "passworddontmatch": "પાસવર્ડ મેળ ખાતો નથી",
  "findpassword": "પાસવર્ડ શોધો",
  "options": "વિકલ્પ",
  "pleaseselectoptiontosendlinkresetpassword":
      "કૃપા કરીને લિંક રીસેટ પાસવર્ડ મોકલવા માટે વિકલ્પ પસંદ કરો",
  "resetviaemail": "ઇમેઇલ દ્વારા ફરીથી સેટ કરો",
  "ifyouhaveemaillinkedtoaccount": "જો તમારી પાસે એકાઉન્ટ સાથે ઇમેઇલ લિંક છે",
  "resetviasms": "એસએમએસ દ્વારા ફરીથી સેટ કરો",
  "skip": "છોડો",
  "start": "શરૂઆત",
  "next": "આગલું",
  "welcometodigitalpost": "ડિજિટલ પોસ્ટ પર આપનું સ્વાગત છે",
  "allbussinessbrandingpost": "બધી બસનેસ બ્રાંડિંગ પોસ્ટ",
  "festivalcategorypost": "મહોત્સવ શ્રેણી",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustry":
      "લોરેમ ઇપ્સમ એ ફક્ત છાપકામ અને ટાઇપસેટિંગ ઉદ્યોગનો ડમી ટેક્સ્ટ છે.",
  "videocategorypost": "વિડિઓ કેટેગરી પોસ્ટ",
  "login": "પ્રવેશ કરો",
  "signup": "સાઇન અપ કરવું",
  "welcomeback": "પાછા આપનું સ્વાગત છે!",
  "enteryouremail": "તમારું ઈમેલ એડ્રેસ લખો",
  "rememberme": "મને યાદ",
  "forgetpassword": "પાસવર્ડ ભૂલી જાઓ",
  "orloginwith": "અથવા સાથે લ log ગ ઇન કરો",
  "registerinbyenteringyouraccountdetails":
      "તમારી એકાઉન્ટ વિગતો દાખલ કરીને નોંધણી કરો.",
  "fullname": "પૂરું નામ",
  "emailaddress": "ઈ - મેઈલ સરનામું",
  "recovery": "પુન: પ્રાપ્તિ",
  "pleaseenteryouremailtorecoveryourpassword":
      "કૃપા કરીને તમારો પાસવર્ડ પુન recover પ્રાપ્ત કરવા માટે તમારું ઇમેઇલ દાખલ કરો",
  "sendlink": "કડી મોકલો",
  "wecannotfindanaccountwiththatemailaddress":
      "અમે તે ઇમેઇલ સરનામાં સાથે એકાઉન્ટ શોધી શકતા નથી",
  "enteryourfullname": "તમારું પૂરું નામ લખો",
  "entervalidemail": "માન્ય ઈ-મેલ દાખલ કરો",
  "postervibe": "છાપો",
  "version": "ભાષાંતર",
  "verification": "ખરાઈ",
  "code": "સંહિતા",
  "verificationcodewassentto": "ચકાસણી કોડ મોકલવામાં આવ્યો હતો",
  "resendcodein": "ઇન -ઇન -ઇન",
  "resend": "-નું કામ કરવું",
  "sendcode": "આચારસંહિતા મોકલો",
  "pleaseentervalidotp": "કૃપા કરીને માન્ય ઓટીપી દાખલ કરો",
  "verifyphone": "ફોન ચકાસો",
  "number": "નંબર",
  "pleaseconfirmyourcountrycodeandenteryourphonenumber":
      "કૃપા કરીને તમારા દેશ કોડની પુષ્ટિ કરો અને તમારો ફોન નંબર દાખલ કરો",
  "phonenumber": "ફોન નંબર",
  "downloads": "ડાઉનલોડ કરવું",
  "review": "સમીક્ષા",
  "invitefriends": "મિત્રોને આમંત્રિત કરો",
  "help": "મદદ",
  "logout": "લૉગ આઉટ",
  "upgradetopro": "પ્રો પર અપગ્રેડ કરવું",
  "oneyearsupportmonthlyupdatesforupto5teammembers":
      "એક વર્ષનો સપોર્ટ, 5 જેટલા ટીમના સભ્યો માટે માસિક અપડેટ્સ.",
  "contactus": "અમારો સંપર્ક કરો",
  "email": "ઇમેઇલ",
  "phone": "કણ",
  "name": "નામ",
  "writeyourmessagehere": "તમારો સંદેશ અહીં લખો",
  "add": "ઉમેરો",
  "namefieldrequired": "નામ ક્ષેત્ર જરૂરી છે",
  "emailfieldrequired": "ઇમેઇલ ફીલ્ડ આવશ્યક છે",
  "messagefieldrequired": "સંદેશ ક્ષેત્ર આવશ્યક છે",
  "digitalpost": "ડિજિટલ પોસ્ટ",
  "all": "બધા",
  "gujrati": "ગુજરાત",
  "hindi": "હિંદી",
  "english": "અંગ્રેજી",
  "images": "છબીઓ",
  "videos": "વિડિઓઝ",
  "editprofile": "પ્રોફાઇલ સંપાદિત કરો",
  "entername": "નામ દાખલ કરવું",
  "enteremail": "ઇમેઇલ દાખલ કરો",
  "birthdate": "જન્મતારીખ",
  "thefullnamefieldisrequired": "સંપૂર્ણ નામ ક્ષેત્ર જરૂરી છે",
  "theemailfieldisrequired": "ઇમેઇલ ફીલ્ડ આવશ્યક છે",
  "thephonenumberfieldisrequired": "ફોન નંબર ફીલ્ડ આવશ્યક છે",
  "pleaseentervalidphonenumber": "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો",
  "thebirthdatefieldisrequired": "જન્મ તારીખ ક્ષેત્ર જરૂરી છે",
  "favorite": "મનપસંદ",
  "filters": "ગાળકો",
  "posttype": "ટપાલ પ્રકાર",
  "festival": "ઉત્સવ",
  "bussiness": "ભવ્યતા",
  "marketing": "બજાર",
  "image": "તસવીર",
  "video": "આદર્શ",
  "free": "મુક્ત",
  "premium": "પ્રીમિયમ",
  "horizontal": "આડા",
  "vertical": "Ticalભું",
  "square": "ચોરસ",
  "panoramic": "વિચિત્ર",
  "categorytype": "શ્રેણીનો પ્રકાર",
  "licensetype": "પરવાના પ્રકાર",
  "colortype": "રંગ પ્રકાર",
  "orientationtype": "અભિગમ પ્રકાર",
  "faq": "ચોરસ",
  "faqandsupport": "FAQ અને ટેકો",
  "didntfindtheansweryouwerelookingforcontactoursupportcenter":
      "તમે જે જવાબ શોધી રહ્યા હતા તે મળ્યું નહીં? અમારા સપોર્ટ સેન્ટરનો સંપર્ક કરો!",
  "gotoourwebsite": "અમારી વેબસાઇટ પર જાઓ",
  "emailus": "અમને ઇમેઇલ કરો",
  "termsofservice": "સેવાની શરતો",
  "search": "શોધ",
  "howdoichangemypassword": "હું મારો પાસવર્ડ કેવી રીતે બદલી શકું?",
  "tochangeyourpasswordproceedtomenuandselectaprofilethenretypeyourcurrentpasswordandclickconfirm":
      "તમારો પાસવર્ડ બદલવા માટે, મેનૂ પર આગળ વધો અને પ્રોફાઇલ પસંદ કરો. પછી તમારો વર્તમાન પાસવર્ડ ફરીથી ટાઇપ કરો અને પુષ્ટિ ક્લિક કરો.",
  "diwali": "દિવાળી",
  "holi": "યહૂદી",
  "makarsankranti": "મકર સંક્રાંતી",
  "upcomingfestival": "આગામી મહોત્સવ",
  "videocategory": "વિડિઓ કેટેગરી",
  "upcamingdayfestival": "અપકેમિંગ દિવસ / તહેવાર",
  "viewall": "બધુજ જુઓ",
  "whenyourfrindssignupwithyourlinkyoullbothgetcharge":
      "જ્યારે તમારી ફ્રાઇન્ડ્સ તમારી લિંક સાથે સાઇન અપ કરે છે ત્યારે તમને બંને \$ 20 ચાર્જ મળશે",
  "link": "સંબંધ",
  "pleaseenteravalidlink": "કૃપા કરીને માન્ય લિંક દાખલ કરો",
  "language": "ભાષા",
  "searchlanguages": "ભાષાની શોધ",
  "notifications": "સૂચના",
  "nonotificationyet": "હજી સુધી કોઈ સૂચના નથી",
  "whenyougetnotificaiontheyllshowuphere":
      "જ્યારે તમને સૂચના મળે, ત્યારે તેઓ ઉથલપાથલ બતાવશે",
  "return": "વળતર",
  "searchnotifications": "શોધ સૂચનો",
  "payment": "ચુકવણી",
  "addnewcard": "નવું કાર્ડ ઉમેરો",
  "addyourdebitcreaditcard": "તમારું ડેબિટ/ક્રેડિટ કાર્ડ ઉમેરો",
  "cardholdername": "કાર્ડ ધારક નું નામ",
  "month": "માસ",
  "year": "વર્ષ",
  "entervalidname": "માન્ય નામ દાખલ કરો",
  "entervalidnumber": "માન્ય નંબર દાખલ કરો",
  "thecardnumbermustcontainatleast16character":
      "કાર્ડ નંબરમાં ઓછામાં ઓછું 16 પાત્ર હોવું આવશ્યક છે",
  "selectexpiredate": "સમાપ્તિ તારીખ પસંદ કરો",
  "entersecuritycode": "સુરક્ષા કોડ દાખલ કરો",
  "thesecuritycodemustcontainatleast3character":
      "સુરક્ષા કોડમાં ઓછામાં ઓછું 3 પાત્ર હોવું આવશ્યક છે",
  "premiumaccess": "પ્રીમિયમ પ્રવેશ",
  "umlimitedpostandvideos": "અમલિમિટેડ પોસ્ટ અને વિડિઓઝ",
  "sharemanagepostvideos": "પોસ્ટ અને વિડિઓઝ શેર કરો અને મેનેજ કરો",
  "automaticdownload": "સ્વચાલિત ડાઉનલોડ",
  "week": "સપ્તાહ",
  "yearly": "વાર્ષિક",
  "weekly": "સાપ્તાહિક",
  "monthly": "દરિયો",
  "3daysfreetrialthenmonthisnotcancelled":
      "3-દિવસો મફત અજમાયશ પછી 99 6.99/મહિનો રદ થયેલ નથી",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustryloremipsumhasbeentheindustrysstandarddummytexteversincethe1500swhenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook":
      "લોરેમ ઇપ્સમ એ ફક્ત છાપકામ અને ટાઇપસેટિંગ ઉદ્યોગનો ડમી ટેક્સ્ટ છે. 1500 ના દાયકાથી લોરેમ ઇપ્સમ એ ઉદ્યોગનો માનક ડમી ટેક્સ્ટ રહ્યો છે, જ્યારે કોઈ અજાણ્યા પ્રિંટરએ ટાઇપની ગેલી લીધી અને તેને ટાઇપ નમૂના પુસ્તક બનાવવા માટે રખડ્યો.",
  "preview": "પૂર્વદર્શન",
  "profile": "રૂપરેખા",
  "setting": "નિર્ધારિત કરવું તે",
  "notification": "સૂચના",
  "shareyourmessagewithothertaxipassenger":
      "તમારા સંદેશને અન્ય ટેક્સી મુસાફરો સાથે શેર કરો.",
  "submit": "રજૂ કરવું",
  "settings": "પતાવટ",
  "option": "વિકલ્પ",
  "thememode": "વિષય -દર",
  "dark": "અંધારું",
  "light": "પ્રકાશ",
  "account": "હિસાબ",
  "personalinformation": "અંગત માહિતી",
  "general": "સામાન્ય",
  "touchidandpasscode": "ટચ આઈડી અને પાસકોડ",
  "privacy": "ગુપ્તતા",
  "other": "બીજું",
  "facebook": "ફેસબુક",
  "appshare": "એ.પી.",
  "share": "હિસ્સો",
  "shareyourlink": "તમારી લિંક શેર કરો",
  "sharetoyourfriendbyusingthese": "આનો ઉપયોગ કરીને તમારા મિત્રને શેર કરો",
  "areyousureyouwanttologout": "શું તમે ખરેખર લ log ગઆઉટ કરવા માંગો છો?",
  "cancel": "રદ કરવું",
};
