final Map<String, String> hiTranslation = {
  "createnew": "नया निर्माण",
  "password": "पासवर्ड",
  "createstrongandsecurepasswordthatprotectyouraccount":
      "मजबूत और सुरक्षित पासवर्ड बनाएं जो आपके खाते की सुरक्षा करते हैं",
  "save": "बचाना",
  "enteryourpassword": "अपना कूटशब्द भरें",
  "yourpasswordisincorrect": "आपका पासवर्ड गलत है",
  "enteryourconfirmpassword": "अपना पुष्टि पासवर्ड दर्ज करें",
  "passworddontmatch": "पासवर्ड मैच मत करो",
  "findpassword": "पासवर्ड पता करो",
  "options": "विकल्प",
  "pleaseselectoptiontosendlinkresetpassword":
      "कृपया लिंक रीसेट पासवर्ड भेजने के लिए विकल्प चुनें",
  "resetviaemail": "ईमेल के माध्यम से रीसेट करें",
  "ifyouhaveemaillinkedtoaccount": "यदि आपके पास ईमेल से जुड़ा हुआ है",
  "resetviasms": "एसएमएस के माध्यम से रीसेट करें",
  "skip": "छोडना",
  "start": "शुरू",
  "next": "अगला",
  "welcometodigitalpost": "डिजिटल पोस्ट में आपका स्वागत है",
  "allbussinessbrandingpost": "सभी bussiness ब्रांडिंग पोस्ट",
  "festivalcategorypost": "त्यौहार श्रेणी पद",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustry":
      "लोरम इप्सम केवल प्रिंटिंग और टाइपसेटिंग उद्योग का डमी टेक्स्ट है।",
  "videocategorypost": "वीडियो श्रेणी पोस्ट",
  "login": "लॉग इन करें",
  "signup": "साइन अप करें",
  "welcomeback": "वापसी पर स्वागत है!",
  "enteryouremail": "अपना ईमेल दर्ज करें",
  "rememberme": "पहचाना की नहीं",
  "forgetpassword": "पासवर्ड भूल गए",
  "orloginwith": "या साथ में लॉग इन करें",
  "registerinbyenteringyouraccountdetails":
      "अपना खाता विवरण दर्ज करके पंजीकरण करें।",
  "fullname": "पूरा नाम",
  "emailaddress": "मेल पता",
  "recovery": "वसूली",
  "pleaseenteryouremailtorecoveryourpassword":
      "अपना पासवर्ड पुनर्प्राप्त करने के लिए कृपया अपना ईमेल दर्ज करें",
  "sendlink": "लिंक भेजें",
  "wecannotfindanaccountwiththatemailaddress":
      "हम उस ईमेल पते के साथ एक खाता नहीं पा सकते हैं",
  "enteryourfullname": "अपना पूरा नाम भरें",
  "entervalidemail": "मान्य ईमेल दर्ज करें",
  "postervibe": "ब्रांड पोस्ट",
  "version": "संस्करण",
  "verification": "सत्यापन",
  "code": "कोड",
  "verificationcodewassentto": "सत्यापन कोड भेजा गया था",
  "resendcodein": "में कोड को फिर से लिखें",
  "resend": "पुन: भेजें",
  "sendcode": "कोड भेजो",
  "pleaseentervalidotp": "कृपया मान्य OTP दर्ज करें",
  "verifyphone": "फोन सत्यापित करें",
  "number": "संख्या",
  "pleaseconfirmyourcountrycodeandenteryourphonenumber":
      "कृपया अपने देश कोड की पुष्टि करें और अपना फ़ोन नंबर दर्ज करें",
  "phonenumber": "फ़ोन नंबर",
  "downloads": "डाउनलोड",
  "review": "समीक्षा",
  "invitefriends": "मित्रों को आमंत्रित करें",
  "help": "मदद",
  "logout": "लॉग आउट",
  "upgradetopro": "प्रो में अपग्रेड",
  "oneyearsupportmonthlyupdatesforupto5teammembers":
      "एक वर्ष का समर्थन, 5 टीम के सदस्यों के लिए मासिक अपडेट।",
  "contactus": "संपर्क करें",
  "email": "ईमेल",
  "phone": "फ़ोन",
  "name": "नाम",
  "writeyourmessagehere": "यहां अपना संदेश लिखें",
  "add": "जोड़ना",
  "namefieldrequired": "नाम फ़ील्ड की आवश्यकता है",
  "emailfieldrequired": "ईमेल फ़ील्ड की आवश्यकता है",
  "messagefieldrequired": "संदेश फ़ील्ड आवश्यक",
  "digitalpost": "डिजिटल पोस्ट",
  "all": "सभी",
  "gujrati": "गुजराती",
  "hindi": "हिंदी",
  "english": "अंग्रेज़ी",
  "images": "इमेजिस",
  "videos": "वीडियो",
  "editprofile": "प्रोफ़ाइल संपादित करें",
  "entername": "नाम दर्ज करें",
  "enteremail": "ईमेल दर्ज करें",
  "birthdate": "जन्म तिथि",
  "thefullnamefieldisrequired": "पूरा नाम फ़ील्ड आवश्यक है",
  "theemailfieldisrequired": "ईमेल क्षेत्र की आवश्यकता है",
  "thephonenumberfieldisrequired": "फ़ोन नंबर फ़ील्ड की आवश्यकता है",
  "pleaseentervalidphonenumber": "कृपया एक वैध नंबर डालें",
  "thebirthdatefieldisrequired": "जन्म तिथि क्षेत्र की आवश्यकता है",
  "favorite": "पसंदीदा",
  "filters": "फिल्टर",
  "posttype": "पद प्रकार",
  "festival": "त्योहार",
  "bussiness": "मास्टर ऑफ बिजनेस",
  "marketing": "विपणन",
  "image": "छवि",
  "video": "वीडियो",
  "free": "मुक्त",
  "premium": "अधिमूल्य",
  "horizontal": "क्षैतिज",
  "vertical": "खड़ा",
  "square": "वर्ग",
  "panoramic": "पैनोरम का",
  "categorytype": "श्रेणी प्रकार",
  "licensetype": "लाइसेंस के प्रकार",
  "colortype": "रंग प्रकार",
  "orientationtype": "अभिविन्यास प्रकार",
  "faq": "सामान्य प्रश्न",
  "faqandsupport": "प्रश्न और समर्थन",
  "didntfindtheansweryouwerelookingforcontactoursupportcenter":
      "वह उत्तर नहीं मिला जो आप देख रहे थे? हमारे समर्थन केंद्र से संपर्क करें!",
  "gotoourwebsite": "हमारी वेबसाइट पर जाएं",
  "emailus": "हमें ईमेल करें",
  "termsofservice": "सेवा की शर्तें",
  "search": "खोज",
  "howdoichangemypassword": "मैं अपना पासवर्ड कैसे बदलूं?",
  "tochangeyourpasswordproceedtomenuandselectaprofilethenretypeyourcurrentpasswordandclickconfirm":
      "अपना पासवर्ड बदलने के लिए, मेनू पर आगे बढ़ें और एक प्रोफ़ाइल चुनें। फिर अपना वर्तमान पासवर्ड रिटाइएप करें और पुष्टि करें पर क्लिक करें।",
  "diwali": "दिवाली",
  "holi": "होली",
  "makarsankranti": "मकर संक्रांति",
  "upcomingfestival": "आगामी त्योहार",
  "videocategory": "वीडियो श्रेणी",
  "upcamingdayfestival": "अपकमिंग डे / फेस्टिवल",
  "viewall": "सभी को देखें",
  "whenyourfrindssignupwithyourlinkyoullbothgetcharge":
      "जब आपके फ्रिंड्स आपके लिंक के साथ साइन अप करते हैं तो आपको दोनों \$ 20 चार्ज मिलेंगे",
  "link": "जोड़ना",
  "pleaseenteravalidlink": "कृपया एक मान्य लिंक दर्ज करें",
  "language": "भाषा",
  "searchlanguages": "खोज भाषाएँ",
  "notifications": "अधिसूचना",
  "nonotificationyet": "अभी तक कोई अधिसूचना नहीं",
  "whenyougetnotificaiontheyllshowuphere":
      "जब आप नोटिसिओन प्राप्त करते हैं, तो वे ऊपर दिखाएंगे",
  "return": "वापस करना",
  "searchnotifications": "खोज सूचनाएँ",
  "payment": "भुगतान",
  "addnewcard": "नया कार्ड जोड़ें",
  "addyourdebitcreaditcard": "अपना डेबिट/क्रेडिट कार्ड जोड़ें",
  "cardholdername": "कार्डधारक का नाम",
  "month": "महीना",
  "year": "वर्ष",
  "entervalidname": "मान्य नाम दर्ज करें",
  "entervalidnumber": "मान्य संख्या दर्ज करें",
  "thecardnumbermustcontainatleast16character":
      "कार्ड नंबर में कम से कम 16 वर्ण होना चाहिए",
  "selectexpiredate": "समाप्ति तिथि का चयन करें",
  "entersecuritycode": "सुरक्षा कोड डाले",
  "thesecuritycodemustcontainatleast3character":
      "सुरक्षा कोड में कम से कम 3 वर्ण होना चाहिए",
  "premiumaccess": "प्रीमियम एक्सेस",
  "umlimitedpostandvideos": "Umlimited पोस्ट और वीडियो",
  "sharemanagepostvideos": "पोस्ट और वीडियो साझा करें और प्रबंधित करें",
  "automaticdownload": "स्वचालित डाउनलोड",
  "week": "सप्ताह",
  "yearly": "सालाना",
  "weekly": "साप्ताहिक",
  "monthly": "महीने के",
  "3daysfreetrialthenmonthisnotcancelled":
      "3-डे फ्री ट्रायल तब \$ 6.99/महीना रद्द नहीं किया गया है",
  "loremipsumissimplydummytextoftheprintingandtypesettingindustryloremipsumhasbeentheindustrysstandarddummytexteversincethe1500swhenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook":
      "लोरम इप्सम केवल प्रिंटिंग और टाइपसेटिंग उद्योग का डमी टेक्स्ट है। लोरम इप्सम 1500 के दशक के बाद से उद्योग का मानक डमी पाठ रहा है, जब एक अज्ञात प्रिंटर ने टाइप की एक गैली ली और एक प्रकार का नमूना पुस्तक बनाने के लिए इसे हाथापाई की।",
  "preview": "पूर्व दर्शन",
  "profile": "प्रोफ़ाइल",
  "setting": "सेटिंग",
  "notification": "अधिसूचना",
  "shareyourmessagewithothertaxipassenger":
      "अन्य टैक्सी यात्री के साथ अपना संदेश साझा करें।",
  "submit": "जमा करना",
  "settings": "समायोजन",
  "option": "विकल्प",
  "thememode": "थीम मोड",
  "dark": "अँधेरा",
  "light": "रोशनी",
  "account": "खाता",
  "personalinformation": "व्यक्तिगत जानकारी",
  "general": "आम",
  "touchidandpasscode": "टच आईडी और पासकोड",
  "privacy": "गोपनीयता",
  "other": "अन्य",
  "facebook": "फेसबुक",
  "appshare": "ऐप शेयर",
  "share": "शेयर करना",
  "shareyourlink": "अपना लिंक साझा करें",
  "sharetoyourfriendbyusingthese": "इनका उपयोग करके अपने दोस्त को साझा करें",
  "areyousureyouwanttologout": "क्या आप लॉग आउट करना चाहते हैं",
  "cancel": "रद्द करना",
};
